from building import *
import rtconfig

# get current directory
cwd     = GetCurrentDir()
# The set of source files associated with this SConscript file.
src     = Glob('*.c')
src     += Glob('i2c_utils.c')
src     += Glob('i2c_tools.c')

path    = [cwd + '/']

LOCAL_CCFLAGS = ''

group = DefineGroup('i2c-tools', src, depend = [''], CPPPATH = path, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
