// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, -10);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner1, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_wifistalabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_wifistalabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifistalabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifistalabel, 0);
    lv_obj_set_y(ui_wifistalabel, 52);
    lv_obj_set_align(ui_wifistalabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifistalabel, "");
    lv_obj_set_style_text_color(ui_wifistalabel, lv_color_hex(0x00FE4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifistalabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_wifistalabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifistalabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgconnSta = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_imgconnSta, &ui_img_connected_png);
    lv_obj_set_width(ui_imgconnSta, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgconnSta, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgconnSta, 0);
    lv_obj_set_y(ui_imgconnSta, -10);
    lv_obj_set_align(ui_imgconnSta, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgconnSta, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgconnSta, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
