// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include <string.h>
#include "esp_log.h"
#include <esp_flash.h>

static const char *TAG = "ui_event";

void lv_setup_system(lv_event_t *e)
{
    // Your code here
    static bool init_flag = false;
    if (init_flag)
    {
        init_flag = true;
        return;
    }

    char err_msg[20];
    esp_err_t status;
    uint64_t unique_out_id;
    if ((status = esp_flash_read_unique_chip_id(NULL, &unique_out_id)) != ESP_OK)
        ESP_LOGE(TAG, "esp_flash_read_id error: %s", esp_err_to_name_r(status, err_msg, sizeof(err_msg)));
    else
        ESP_LOGI(TAG, "Chip unique out_id: %" PRId64 "", unique_out_id);

    char uni_base[18];
    sprintf(uni_base, "%lld", unique_out_id);
    lv_label_set_text(ui_Systext, uni_base);
}
